# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

raw_data: "scripts/data/penguins.csv"

# One directory up from the working directory.
# From this point on I can specify the result directory and its subdirectories.
# IMPORTANT: THIS PATH MUST BE CHANGED when I move the project folder!!
playground_dir: "/Users/corrado/_repositories/snakemake_playground/playground/"


# Folders created in output by the rules. This list is used in the clean rule to
# remove all the outputs that have been created.
RES_DIRS: ["logs", "plots", "tables", "data", "reports"]
