# Snakemake playground workflow
#
# @ccaudek


# Require Snakemake >= this version
from snakemake.utils import min_version
min_version("6.12.3")

configfile: "../config/config.yaml"

report: "report/workflow.rst"

rule all:
    input:
        "../results/plots/figure_1.pdf",
        "../results/plots/figure_2.pdf",
        "../results/data/processed/penguin_subset.rds",
        "../results/tables/tab_1.txt",
        "../results/plots/hist_1.pdf",
        "../results/reports/report.html",


include: "rules/common.smk"
include: "rules/eda.smk"
include: "rules/histogram.smk"
include: "rules/render_report.smk"
