# Snakemake playground workflow
#
# @ccaudek


# Require Snakemake >= this version
from snakemake.utils import min_version
min_version("6.12.3")

from pathlib import Path
import os

# print(f"Working directory: {os.getcwd()}")
print(f"Current directory: {Path.cwd()}")
print(f"Home directory: {Path.home()}")
path_wd = Path.cwd();
print(f"Parent of working directory: {path_wd.parent}")
# print(path_wd.parent)
# print(os.path.join(path_wd.parent, "results/plots/figure_1.pdf"))

my_basedir = workflow.current_basedir

configfile: "../config/config.yaml"

report: "report/workflow.rst"

rule targets:
    input:
        "../results/plots/figure_1.pdf",
        "../results/plots/figure_2.pdf",
        "../results/data/processed/penguin_subset.rds",
        "../results/tables/tab_1.txt",
        "../results/plots/hist_1.pdf",
        "../results/reports/report.html",
        "../results/brms/fit_01.rds",
        "../results/brms/table_1.csv"
        #"scripts/reports/my_report.html"


include: "rules/common.smk"
include: "rules/eda.smk"
include: "rules/histogram.smk"
include: "rules/brm_fit_model.smk"


# Because of the directory structure, it is simpler to put the make_report
# rule in the Snakefile.

# It is not possible to specify the address of the figures in `input:`, because
# after a clean such figures do not exist. Instead, the address of the figures
# that is created *before* the make_report rule is executed is specified in
# `params:`. Because the `results` folder is one level up from the working
# directory, the specification of the path is obtained with the method described
# in the README.md file.
# Another method is to specify the first part of the path (until `playground`)
# in the config.yaml file, and then to add the second part of the path as
# indicated in the commented line.

rule make_report:
    input:
        data=config["raw_data"],
        subset_data="../results/data/processed/penguin_subset.rds",
        table_data=rules.save_table.output.tab1
    output:
        "../results/reports/report.html"
    params:
        #pdf_fig1=config["playground_dir"] + "results/plots/figure_1.pdf"
        pdf_fig1=os.path.join(path_wd.parent, "results/plots/figure_1.pdf")
    log:
        mylog="../results/logs/make_report.log"
    script:
        "scripts/reports/report.Rmd"


## This is an alternative way to knit the Rmd file. It achieves the same
## result as the one above.
#
# rule my_report:
#     input:
#         R="scripts/reports/render.R",
#         rmd="scripts/reports/my_report.Rmd"
#     params:
#         plots_dir=config["playground_dir"] + "results/plots/"
#     output:
#         html="scripts/reports/my_report.html"
#     script:
#         "scripts/reports/render.R"
